"""Add Todo table

Revision ID: 9c99d61de59e
Revises:
Create Date: 2026-07-17 15:05:15.966444

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9c99d61de59e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("_prisma_migrations")
    op.drop_table("playing_with_neon")
    op.drop_table("Task")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Task",
        sa.Column("id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "isCompleted",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.INTEGER(),
            server_default=sa.text("5"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "dueDate",
            postgresql.TIMESTAMP(precision=3),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("category", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "createdAt",
            postgresql.TIMESTAMP(precision=3),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            postgresql.TIMESTAMP(precision=3),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("Task_pkey")),
    )
    op.create_table(
        "playing_with_neon",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("value", sa.REAL(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("playing_with_neon_pkey")),
    )
    op.create_table(
        "_prisma_migrations",
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column(
            "checksum", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "finished_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "migration_name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("logs", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "rolled_back_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "applied_steps_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("_prisma_migrations_pkey")),
    )
    # ### end Alembic commands ###
